name: Build SEB for Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install WiX Toolset 3.14
        run: |
          choco install wixtoolset --version=3.14.1.20250415 -y

      - name: Verify WiX installation
        run: |
          & "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe" -?
          & "C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe" -?

      - name: Build SEB
        run: |
          dotnet restore SafeExamBrowser.sln
          dotnet build SafeExamBrowser.sln -c Release
          dotnet publish SafeExamBrowser.Runtime/SafeExamBrowser.Runtime.csproj -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --output ./build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SEB-Windows
          path: ./build/
