name: Build SEB Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: nuget restore SafeExamBrowser.sln

    - name: Build project
      run: dotnet publish SafeExamBrowser.sln -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --output ./build

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: SEB-Windows-Build
        path: ./build
